### ISSUE TITLE
Focus on Widgets

### ISSUE THREAD

**Issue by fernandohds564** [lnls-sirius/org.csstudio.product#6]
According to the CS-Studio Help, when we click on a Scrollbar widget or a ThumbWhell widget it should be focused, which would allow us to control them with keyboard keys. This is not happening in version 4.4.2.

**Comment by gciotto** [comment]
In our release, I added the following argument to the file `cs-studio.ini`:
```
--launcher.GTK_version
2
```
Apparently, it is causing those problems with the focus. I'm going to correct this configuration in our repo. If you want to test it before I create the new product, just remove the two lines above from the file `cs-studio.ini`, present in the root folder of your product.

I appended this argument because I was facing some problems with my Eclipse, then I thought CSS might suffer the same. However,  CSS uses an older version (Mars) than I'm currently using (Neon). I'm going to study more on GTK, but I think this issue is solved.

**Comment by fernandohds564** [comment]
I tried to remove de mentioned lines, but it didn't work, @gciotto.

**Comment by gciotto** [comment]
Previously, I had tested only version `4.3.x` and it worked. The focus and key events are currently working in this version. Unfortunately, from this version onward, I could not get them working. OPI Builder is based on the [GEF (Graphical Editing Framework) 3](http://www.eclipse.org/gef/), which is not directly compatible with eclipse 4, which the latest CCS  version are built from.  OPI builder can still be executed thanks to the [compatibility layer](http://www.vogella.com/tutorials/Eclipse4MigrationGuide/article.html#using-the-eclipse-3-x-api-on-top-of-an-4-x-runtime) that is part of e4, but I believe that this issue comes exactly from it. I read the code of Scrollbar component and its listeners for keyboard and focus events are configured correctly. In short, I could not find what is the exact problem. 
A new interface builder is being developed for e4 and its name is [DisplayBuilder](https://github.com/kasemir/org.csstudio.display.builder). According to the REAME.md, it can read files with extension `.opi`, therefore all the interfaces we made so far will not have to be redrawn. My next steps are to test and add it to our releases.

**Comment by fernandohds564** [comment]
Thank you @gciotto. I will wait for the new releases.

**Comment by gciotto** [comment]
I've added the DisplayBuilder feature to our releases, among some other minor changes. In addition, I've changes some Channel Access options to point a machine in Control's network. Any problems, please tell me!

**Comment by fernandohds564** [comment]
I downloaded the release 4.5.1 and installed it in my computer. I noticed the DisplayBuilder options under Preferences -> CSS Applications -> Display, but I don't know how to use it to solve the focus issue.
Could you help me with that?
Thanks!

**Comment by gciotto** [comment]
Some more info about DisplayBuilder at [here](https://conference.sns.gov/event/11/session/1/contribution/17). Slides from 18 to 20 give some interesting feedback about the changes in scripts.
